import CoreGraphics
import CoreImage
import Foundation
import ImageIO
import Synchronization

/// One entry of Resources/LUTs/catalog.json (generated by the LUT converter).
struct LUTInfo: Codable, Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let brand: String
    let group: String
    let size: Int
    let bits: Int
    let file: String
}

/// A decoded 3D LUT, ready for CIColorCubeWithColorSpace (float RGBA, red fastest, then green, then blue).
struct CubeLUT: Sendable {
    let dimension: Int
    let data: Data
}

struct FilterSelection: Codable, Equatable, Sendable {
    var id: String
    var intensity: Float = 1
}

/// Loads and caches LUTs. Thread-safe; used from the UI, the video queue and capture.
final class LUTLibrary: Sendable {
    static let shared = LUTLibrary()

    let catalog: [LUTInfo]
    let brands: [String]
    private let byID: [String: LUTInfo]
    private let directory: URL?
    private let cache = Mutex<[String: CubeLUT]>([:])
    private let cacheOrder = Mutex<[String]>([])
    private static let cacheLimit = 24   // up to ~96 MB for 64³ cubes

    init(bundle: Bundle = .main) {
        // The Lock Screen camera extension doesn't carry its own copy of the 73 MB library; it
        // reads the containing app's (…/TrueShot.app/Extensions/X.appex → …/TrueShot.app).
        let appBundleURL = bundle.bundleURL.deletingLastPathComponent().deletingLastPathComponent()
        let dir = bundle.url(forResource: "LUTs", withExtension: nil)
            ?? (AppRuntime.isExtension ? Bundle(url: appBundleURL)?.url(forResource: "LUTs", withExtension: nil) : nil)
        directory = dir
        if let dir, let data = try? Data(contentsOf: dir.appending(path: "catalog.json")),
           let list = try? JSONDecoder().decode([LUTInfo].self, from: data) {
            catalog = list
        } else {
            catalog = []
        }
        byID = Dictionary(uniqueKeysWithValues: catalog.map { ($0.id, $0) })
        var seen = Set<String>()
        brands = catalog.map(\.brand).filter { seen.insert($0).inserted }
    }

    func info(_ id: String) -> LUTInfo? { byID[id] }

    func cube(for id: String) -> CubeLUT? {
        if let hit = cache.withLock({ $0[id] }) { return hit }
        guard let info = byID[id], let directory,
              let cube = try? Self.decode(url: directory.appending(path: info.file), expectedSize: info.size) else { return nil }
        cache.withLock { $0[id] = cube }
        let evicted: [String] = cacheOrder.withLock { order in
            order.removeAll { $0 == id }
            order.append(id)
            guard order.count > Self.cacheLimit else { return [] }
            let drop = Array(order.prefix(order.count - Self.cacheLimit))
            order.removeFirst(drop.count)
            return drop
        }
        if !evicted.isEmpty { cache.withLock { for key in evicted { $0[key] = nil } } }
        return cube
    }

    /// Decode a strip PNG (width n·n, height n; pixel (b·n + r, g) = output for input (r, g, b)).
    ///
    /// The image is drawn into a 16-bit context in *its own* colour space, so Core Graphics
    /// performs no colour conversion: 8-bit values arrive as v·257 and 16-bit values unchanged.
    static func decode(url: URL, expectedSize: Int) throws -> CubeLUT {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, [kCGImageSourceShouldCache: false] as CFDictionary)
        else { throw LUTError.unreadable }
        let n = image.height
        guard n == expectedSize, image.width == n * n, n >= 2, n <= 128 else { throw LUTError.badDimensions }
        guard let space = image.colorSpace, space.model == .rgb else { throw LUTError.badColorSpace }

        let width = image.width
        let bytesPerRow = width * 8
        var pixels = [UInt16](repeating: 0, count: width * n * 4)
        let drawn: Bool = pixels.withUnsafeMutableBytes { buffer in
            guard let context = CGContext(data: buffer.baseAddress, width: width, height: n,
                                          bitsPerComponent: 16, bytesPerRow: bytesPerRow, space: space,
                                          bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue | CGBitmapInfo.byteOrder16Little.rawValue)
            else { return false }
            context.interpolationQuality = .none
            context.setBlendMode(.copy)
            context.draw(image, in: CGRect(x: 0, y: 0, width: width, height: n))
            return true
        }
        guard drawn else { throw LUTError.unreadable }

        // Row 0 of a bitmap context's memory is the top row of the drawn image.
        var cube = [Float](repeating: 1, count: n * n * n * 4)
        let scale = 1 / Float(65535)
        for b in 0..<n {
            for g in 0..<n {
                for r in 0..<n {
                    let src = (g * width + b * n + r) * 4
                    let dst = ((b * n + g) * n + r) * 4
                    cube[dst] = Float(UInt16(littleEndian: pixels[src])) * scale
                    cube[dst + 1] = Float(UInt16(littleEndian: pixels[src + 1])) * scale
                    cube[dst + 2] = Float(UInt16(littleEndian: pixels[src + 2])) * scale
                }
            }
        }
        return CubeLUT(dimension: n, data: cube.withUnsafeBufferPointer { Data(buffer: $0) })
    }

    /// The LUTs were authored for gamma-encoded sRGB, so the lookup happens in sRGB.
    /// `intensity` blends between the original (0) and the fully filtered image (1).
    static func apply(_ cube: CubeLUT, to image: CIImage, intensity: Float) -> CIImage {
        let filter = CIFilter(name: "CIColorCubeWithColorSpace")
        filter?.setValue(image, forKey: kCIInputImageKey)
        filter?.setValue(cube.dimension, forKey: "inputCubeDimension")
        filter?.setValue(cube.data, forKey: "inputCubeData")
        filter?.setValue(CGColorSpace(name: CGColorSpace.sRGB), forKey: "inputColorSpace")
        guard let filtered = filter?.outputImage else { return image }
        let t = intensity.clamped(to: 0...1)
        if t >= 0.999 { return filtered }
        if t <= 0.001 { return image }
        let blend = CIFilter(name: "CIDissolveTransition")
        blend?.setValue(image, forKey: kCIInputImageKey)
        blend?.setValue(filtered, forKey: kCIInputTargetImageKey)
        blend?.setValue(t, forKey: kCIInputTimeKey)
        return blend?.outputImage?.cropped(to: image.extent) ?? filtered
    }
}

enum LUTError: Error {
    case unreadable, badDimensions, badColorSpace
}
